### ISSUE TITLE
Add a generic graphics driver

### ISSUE THREAD

**Issue by nbulischeck** [nbulischeck/VexSys#18]
The Arch wiki has a couple options of drivers to install. Most likely going to go with the xf86 vesa driver.

https://wiki.archlinux.org/index.php/xorg#Installation

**Comment by PedroSFreitas** [comment]
@nbulischeck,

If you check https://wiki.archlinux.org/index.php/xorg#Driver_installation, you'll see there is a package called `xorg-drivers` that will install:
![image](https://user-images.githubusercontent.com/12863160/37303861-90020158-260e-11e8-9929-52e48eec9cad.png)
